beauty/urls.py
from django.urls import path
from . import views, views_data

app_name = 'beauty'

urlpatterns = [
    path('create_test_DB', views_data.create_test_DB, name="create_test_DB"),
    path('create_test_csv', views_data.create_test_csv, name="creat_test_csv"),
    path('convert_xlsx_to_csv', views_data.convert_xlsx_to_csv, name="convert_xlsx_to_csv"),
    path('create_category_csv', views_data.create_category_csv, name="create_category_csv"),
    path('cosmetic_edit/<int:num>', views_data.cosmetic_edit, name="cosmetic_edit"),
    path('processing_csv', views_data.processing_csv, name="processing_csv"),

    path('', views.home, name="home"),
    path('video/', views.video_list, name="video_list"),
    path('video/<str:period>', views.video_list, name="video_list"),
    path('video_scrap', views.video_scrap, name="video_scrap"),

    path('cosmetic/', views.cosmetic_list, name="cosmetic_list"),
    path('cosmetic/<str:kind>', views.cosmetic_list, name="cosmetic_list"),
    path('cosmetic_scrap', views.cosmetic_scrap, name="cosmetic_scrap"),

    path('combine/result', views.combine_result, name="combine_result"),
    path('combine_processing', views.combine_processing, name="combine_processing"),

    path('combine/', views.combine_cosmetic, name="combine_cosmetic"),
    path('combine/<str:kind>', views.combine_cosmetic, name="combine_cosmetic"),
    
    path('cosmetic_pick', views.cosmetic_pick, name="cosmetic_pick"),
    path('cosmetic_delete', views.cosmetic_delete, name="cosmetic_delete"),
    path('cosmetic_reset', views.cosmetic_reset, name="cosmetic_reset"),

    path('cosmetic_save', views.cosmetic_save, name="cosmetic_save"),
    path('recommend_scrap', views.recommend_scrap, name="recommend_scrap"),

    path('search', views.search, name="search"),
]

veauty_inside/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('', lambda r:redirect('beauty:home'), name='root'),
    path('admin/', admin.site.urls),
    path('beauty/', include('beauty.urls')),
    path('accounts/', include('accounts.urls')),
]

beauty/models.py
from django.db import models

# Create your models here.
class Youtuber(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Video(models.Model):
    title = models.CharField(max_length=50)
    yt_url = models.URLField(max_length=200)
    youtuber = models.ForeignKey("Youtuber", verbose_name="youtuber", on_delete=models.CASCADE)
    cosmetic = models.ManyToManyField("Cosmetic")
    upload_at = models.DateField(auto_now=False, auto_now_add=False)
    hits = models.IntegerField()

    class Meta:
        ordering = ['hits', 'title']

    def __str__(self):
        return self.title

class Bigcate(models.Model):
    name = models.CharField(max_length=50)
    eng_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Smallcate(models.Model):
    bigcate = models.ForeignKey("Bigcate", verbose_name="bigcate", on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    eng_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Cosmetic(models.Model):
    category = models.ForeignKey("Smallcate", verbose_name="category", on_delete=models.CASCADE)
    name = models.CharField(max_length=240, db_index=True)

    def __str__(self):
        return self.name

beauty/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.messages import get_messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from .models import Youtuber, Video, Cosmetic, Bigcate, Smallcate
from urllib import parse
from . import message_string as msg
import datetime

COSMETIC_SELECTION = {
    'all' : 'all',
    'interest' : 'interest',
    'my' : 'my',
}

def redirect_with_query(url_path, querystring, url_parameter=""):
    if url_parameter:
        response = redirect(url_path, url_parameter)
    else:
        response = redirect(url_path)
        
    response['Location'] += querystring
    
    return response

def pagination(request, contexts, contexts_name, PAGE_ROW_COUNT=10, PAGE_DISPLAY_COUNT=10):
    paginator=Paginator(contexts, PAGE_ROW_COUNT)
    pageNum=request.GET.get('pageNum') # 현재 페이지
    
    totalPageCount=paginator.num_pages # 전체 페이지 갯수 
    
    try:
        contexts = paginator.page(pageNum)
    except PageNotAnInteger:
        contexts = paginator.page(1)
        pageNum = 1
    except EmptyPage:
        contexts = paginator.page(paginator.num_pages)
        pageNum = paginator.num_pages
        
    pageNum = int(pageNum)
    
    startPageNum = 1 + PAGE_DISPLAY_COUNT * int((pageNum - 1)/PAGE_DISPLAY_COUNT)
    endPageNum = startPageNum + PAGE_DISPLAY_COUNT-1

    if totalPageCount < endPageNum:
        endPageNum = totalPageCount
        
    bottomPages = range(startPageNum, endPageNum+1)

    return {
        contexts_name: contexts,
        'PAGE_ROW_COUNT' : PAGE_ROW_COUNT,
        'pageNum': pageNum,
        'bottomPages': bottomPages,
        'totalPageCount': totalPageCount,
        'startPageNum': startPageNum,
        'endPageNum': endPageNum,
    }

def home(request):
    return render(request, 'beauty/home.html')

def video_list(request, period=""):
    today = datetime.datetime.now()
    year = today.year
    month = today.month
    seven_days = datetime.timedelta(days=7)

    VIDEO_FILTER = {
        "all" : Video.objects.all().order_by('-hits'),
        "month" : Video.objects.filter(upload_at__month=month).filter(upload_at__year=year).order_by('-hits'),
        "week" : Video.objects.filter(upload_at__gte=(today-seven_days)).order_by('-hits'),
    }

    if period == "":
        period = list(VIDEO_FILTER.keys())[0]

    videos = VIDEO_FILTER.get(period, None)

    if videos is None:
        return redirect("beauty:home")

    contexts = pagination(request, videos, 'videos')
    contexts.update({
        'period' : period,
        'big_categories' : Bigcate.objects.all(),
    })

    return render(request, 'beauty/video_list.html', contexts)

def video_scrap(request):
    if request.method == 'POST':
        videos = Video.objects.filter(pk__in=request.POST.getlist("video_id"))

        if videos:
            request.user.video.add(*videos)
            messages.success(request, msg.VIDEO_SCRAP)
        else:
            messages.warning(request, msg.NO_VIDEO_SELECT)

    if request.GET.get('q'):
        return redirect_with_query("beauty:search", '?q='+parse.quote(request.GET['q']))
    else:
        return redirect_with_query("beauty:video_list", '?pageNum='+request.POST['pageNum'], request.POST['period'])

def list_for_cosmetic(request, kind, combinate=False, PAGE_ROW_COUNT=10):
    contexts = {}

    try:
        smallcate = Smallcate.objects.get(eng_name=kind)

        #COSMETIC_FILTER insert necessary cosmetic instances
        cosmetics = Cosmetic.objects.filter(category=smallcate).annotate(count=Count('video')).order_by('-count')

        #contexts update
        contexts.update({
            'curr_small' : smallcate,
            'curr_big' : smallcate.bigcate,
            'small_categories' : smallcate.bigcate.smallcate_set.all(),
        })
    except Smallcate.DoesNotExist:
        #'cosmetic/' is same with 'cosmetic/all'
        if kind == "":
            kind = COSMETIC_SELECTION['all']

        COSMETIC_FILTER = {
            COSMETIC_SELECTION['all'] : Cosmetic.objects.annotate(count=Count('video')).order_by('-count'),
        }
        
        #COSMETIC_FILTER update at coemetic combaine page and user login state
        if combinate and request.user.is_authenticated:
            COSMETIC_FILTER.update({
                COSMETIC_SELECTION['interest'] : request.user.cosmetic.all().annotate(count=Count('video')).order_by('-count'),
                COSMETIC_SELECTION['my'] : request.user.my_cosmetic.all().annotate(count=Count('video')).order_by('-count'),
            })
    
        cosmetics = COSMETIC_FILTER.get(kind, None)

    if cosmetics is None:
        return 0
    else:
        contexts.update(pagination(request, cosmetics, 'cosmetics', PAGE_ROW_COUNT))
        contexts.update({
            'kind' : kind,
            'big_categories' : Bigcate.objects.all(),
        })

        return contexts

def cosmetic_list(request, kind=""):
    contexts = list_for_cosmetic(request, kind, combinate=False, PAGE_ROW_COUNT=10)
    if contexts == 0:
        return redirect("beauty:home")
    else:
        youtube_num = 5
        contexts.update({
            'yt_num' : youtube_num,
            'yt_range' : range(youtube_num),
        })
        return render(request, 'beauty/cosmetic_list.html', contexts)

def cosmetic_scrap(request):
    if request.method == 'POST':
        cosmetics = Cosmetic.objects.filter(pk__in=request.POST.getlist("cosmetic_id"))

        if request.POST['selection'] == COSMETIC_SELECTION['interest']:
            if cosmetics:
                request.user.cosmetic.add(*cosmetics)
                messages.success(request, msg.INTEREST_COS_SCRAP)
            else:
                messages.warning(request, msg.NO_INTEREST_SELECT)

        elif request.POST['selection'] == COSMETIC_SELECTION['my']:
            if cosmetics:
                request.user.my_cosmetic.add(*cosmetics)
                messages.success(request, msg.MY_COS_SCRAP)
            else:
                messages.warning(request, msg.NO_MY_SELECT)

    if request.GET.get('q'):
        return redirect_with_query("beauty:search", '?q='+parse.quote(request.GET['q']))
    else:
        return redirect_with_query("beauty:cosmetic_list", '?pageNum='+request.POST['pageNum'], request.POST['kind'])

def combine_cosmetic(request, kind=""):
    contexts = list_for_cosmetic(request, kind, combinate=True, PAGE_ROW_COUNT=15)
    storage = get_messages(request)
    for message in storage:
        contexts.update({
            'message_tags' : message.tags.split(" ")[1]
        })

    if contexts == 0:
        return redirect("beauty:home")
    else:
        contexts.update({
            'selected' : [get_object_or_404(Cosmetic, pk=pk) for pk in request.GET.getlist('c')],
            'query_cos' : (lambda x: '?c=' + '&c='.join(x) if x else "")(request.GET.getlist('c')),
        })
        return render(request, 'beauty/combine_cosmetic.html', contexts)

def cosmetic_pick(request):
    if request.method == "POST":
        querystring = request.POST['curr_query']
        cosmetics_id_list = request.POST.getlist('cosmetic_id')
        if cosmetics_id_list:
            query_list = querystring.split('&')

            for cos_id in cosmetics_id_list:
                cos_id_query = "c=" + cos_id

                if not cos_id_query in query_list:
                    querystring = querystring + "&c=" + cos_id

            messages.success(request, msg.PUT_IN_BASKET, extra_tags='pick')
        else:
            messages.warning(request, msg.NO_BASKET_SELECT, extra_tags='pick')
            
        return redirect_with_query("beauty:combine_cosmetic", '?' + querystring, request.POST['kind'])
    else:
        return redirect("beauty:combine_cosmetic", COSMETIC_SELECTION['all'])

def cosmetic_delete(request):
    if request.method == "POST":
        querystring = request.POST['curr_query']

        delete_query_list = ["c="+del_cos for del_cos in request.POST.getlist('del_cos')]
        if delete_query_list:
            query_list = querystring.split('&')
            query_list = [query_item for query_item in query_list if query_item not in delete_query_list]
            
            querystring = "&".join(query_list)

            messages.success(request, msg.DELETE_COS_IN_BASKET, extra_tags='basket')
        else:
            messages.warning(request, msg.NO_DELETE_COS, extra_tags='basket')
        
        return redirect_with_query("beauty:combine_cosmetic", '?' + querystring, request.POST['kind'])
    else:
        return redirect("beauty:combine_cosmetic", COSMETIC_SELECTION['all'])

def cosmetic_reset(request):
    if request.method == "POST":
        query_list = request.POST['curr_query'].split('&')
        cosmetic_have = False
        temp_list = []

        for query_item in query_list:
            if query_item[:2] == "c=":
                cosmetic_have = True
            else:
                temp_list.append(query_item)
        querystring = "&".join(temp_list)

        if cosmetic_have:
            messages.success(request, msg.RESET_BASKET, extra_tags='basket')
        else:
            messages.warning(request, msg.NO_BASKET, extra_tags='basket')

        return redirect_with_query("beauty:combine_cosmetic", '?' + querystring, request.POST['kind'])
    else:
        return redirect("beauty:combine_cosmetic", COSMETIC_SELECTION['all'])

def combine_processing(request):
    if request.method == 'POST':
        querystring = request.POST['curr_query']

        cosmetic_have = False
        for query_item in querystring.split('&'):
            if query_item[:2] == "c=":
                cosmetic_have = True
                break

        if cosmetic_have:
            return redirect_with_query("beauty:combine_result", '?' + querystring)
        else:
            messages.warning(request, msg.NO_BASKET, extra_tags='basket')

beauty/templates/beauty/category_edit.html
{% load custom_tags %}

<form action="" method="post">
    {% csrf_token %}
    {% for i in range %}
    {{ i }}
    <br>
    {% for cate in row_cate|index:i  %}
    <input type="text" name="{{i}},{{forloop.counter0}}" value="{{cate}}">
    {% endfor %}
    <br>
    <input type="submit">
    <hr />
    {% endfor %}
    <input type="submit" name="add" value="add">
</form>

beauty/templates/beauty/combine_cosmetic.html
{% extends 'beauty/base.html' %}

{% block title %}
Veauty Inside - Combination
{% endblock %}

{% block content %}
<div class="container-fluid mt-1">
    <div class="row">
        <div class="col-sm-12 col-md-7 col-lg-8">
            {% if messages %}
            {% for message in messages %}
            {% if 'pick' in message.tags %}
            <div class="alert alert-{{ message_tags }} alert-dismissable show fade mt-1" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
        <div class="col-sm-12 col-md-5 col-lg-4">
            {% if messages %}
            {% for message in messages %}
            {% if 'basket' in message.tags %}
            <div class="alert alert-{{ message_tags }} alert-dismissable show fade mt-1" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-7 col-lg-8">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link {% if kind == 'all' %} active {% endif %}"
                        href="{% url 'beauty:combine_cosmetic' 'all' %}{{ query_cos }}">전체 화장품</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if kind == 'interest' %} active {% endif %}"
                        href="{% url 'beauty:combine_cosmetic' 'interest' %}{{ query_cos }}">관심 화장품</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if kind == 'my' %} active {% endif %}"
                        href="{% url 'beauty:combine_cosmetic' 'my' %}{{ query_cos }}">내 화장품</a>
                </li>
                {% endif %}
                {% for big_category in big_categories %}
                <li class="nav-item">
                    <a class="nav-link {% if big_category == curr_big %} active {% endif %}"
                        href="{% url 'beauty:combine_cosmetic' big_category.smallcate_set.all.0.eng_name %}{{ query_cos }}">{{ big_category }}</a>
                </li>
                {% endfor %}
            </ul>
            {% if kind != 'all' %}
            <ul class="nav nav-tabs mt-1">
                {% for small_category in small_categories %}
                <li class="nav-item">
                    <a class="nav-link {% if small_category == curr_small %} active {% endif %}"
                        href="{% url 'beauty:combine_cosmetic' small_category.eng_name %}{{ query_cos }}">{{ small_category }}</a>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="{% url 'beauty:cosmetic_pick' %}" method="post">
                {% csrf_token %}
                <div class="scroll-wrap  mb-1 combine-table">
                    <div class="scrolling table-responsive scrollbar-lady-lips thin square">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="vid-select text-center"><span><i class="fa fa-check"></i></span></th>
                                    <th class="text-center">랭킹</th>
                                    {% if kind == 'all' %}
                                    <th>분류</th>
                                    {% endif %}
                                    <th>제품</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cosmetic in cosmetics %}
                                {% load mathfilters %}
                                <tr>
                                    <td>
                                        <div class="custom-control custom-checkbox d-inline">
                                            <input type="checkbox" class="custom-control-input" name="cosmetic_id"
                                                id="customCheck{{ cosmetic.id }}" value="{{ cosmetic.id }}">
                                            <label class="custom-control-label"
                                                for="customCheck{{ cosmetic.id }}"></label>
                                        </div>
                                    </td>
                                    <td class="text-center">
                                        {% if pageNum %}
                                        {{ pageNum|mul:PAGE_ROW_COUNT| sub:PAGE_ROW_COUNT |add:forloop.counter }}
                                        {% else %}
                                        {{ forloop.counter }}
                                        {% endif %}
                                    </td>
                                    {% if kind == 'all' %}
                                    <td>{{ cosmetic.category }}</td>
                                    {% endif %}
                                    <td>{{ cosmetic.name }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <input type="hidden" name="kind" value="{{ kind }}">
                <input type="hidden" name="curr_query" value="{{ request.GET.urlencode }}">
                <div class="text-right">
                    <button type="submit" class="btn btn-primary mt-auto col-4 col-sm-3 col-md-4 col-lg-3">화장품
                        담기</button>
                </div>
                {% include 'beauty/pagination.html' %}
            </form>
        </div>
        <div class="col-sm-12 col-md-5 col-lg-4">
            <div class="d-flex justify-content-center align-items-center border border-primary rounded mb-1">
                <h5 class="m-2 font-weight-normal text-primary"><i class="fa fa-shopping-basket" aria-hidden="true"></i>
                </h5>
            </div>
            <form action="{% url 'beauty:cosmetic_delete' %}" method="post">
                {% csrf_token %}
                <div class="scroll-wrap mb-1 combine-list-table">
                    <div class="scrolling table-responsive scrollbar-lady-lips thin square">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="text-center"><span><i class="fa fa-check"></i></span></th>
                                    <th>분류</th>
                                    <th>제품</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for selection in selected %}
                                <tr>
                                    <td>
                                        <div class="custom-control custom-checkbox d-inline">
                                            <input type="checkbox" class="custom-control-input" name="del_cos"
                                                id="customCheck1{{ selection.id }}" value="{{ selection.id }}">
                                            <label class="custom-control-label"
                                                for="customCheck1{{ selection.id }}"></label>
                                        </div>
                                    </td>
                                    <td>{{ selection.category }}</td>
                                    <td>{{ selection.name }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="cosmetic-combine text-right">
                    <input type="hidden" name="kind" value="{{ kind }}">
                    <input type="hidden" name="curr_query" value="{{ request.GET.urlencode }}">
                    <button type="submit" class="btn btn-primary mt-auto col-4 col-sm-3 col-md-5 col-lg-5">목록에서
                        제거</button>
                </div>
            </form>

            <div class="cosmetic-combine text-right">
                <form action="{% url 'beauty:cosmetic_reset' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="kind" value="{{ kind }}">
                    <input type="hidden" name="curr_query" value="{{ request.GET.urlencode }}">
                    <button type="submit" class="btn btn-primary mt-auto col-4 col-sm-3 col-md-5 col-lg-5">목록
                        초기화</button>
                </form>
            </div>

            <div class="cosmetic-combine text-right">
                <form action="{% url 'beauty:combine_processing' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="kind" value="{{ kind }}">
                    <input type="hidden" name="curr_query" value="{{ request.GET.urlencode }}">
                    <button type="submit" class="btn btn-primary mt-auto col-4 col-sm-3 col-md-5 col-lg-5">결과
                        보기</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

beauty/templates/beauty/combine_result.html
{% extends 'beauty/base.html' %}

{% block title %}
Combine Result
{% endblock %}

{% block content %}
<div class="container-fluid mt-1">
    <div class="row">
        <div class="col-sm-12 col-md-4">
            {% if messages %}
            {% for message in messages %}
            {% if 'cosmetic' in message.tags %}
            <div class="alert alert-{{ message_tags }} alert-dismissable show fade mt-1" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
        <div class="col-sm-12 col-md-8">
            {% if messages %}
            {% for message in messages %}
            {% if 'video' in message.tags %}
            <div class="alert alert-{{ message_tags }} alert-dismissable show fade mt-1" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <div class="scroll-wrap mb-1 result-table">
                <div class="scrolling table-responsive scrollbar-lady-lips thin square">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>선택한 화장품</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cosmetic in cosmetics %}
                            <tr>
                                <td>{{ cosmetic.name }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <form action="{% url 'beauty:cosmetic_save' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="curr_query" value="{{ request.GET.urlencode }}">
                <div class="row d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary mt-auto col-5 col-md-8 col-lg-5 mr-1" name="selection"
                        value="interest">관심 화장품 등록</button>
                    <button type="submit" class="btn btn-primary mt-auto col-5 col-md-8 col-lg-5" name="selection" value="my">내 화장품
                        등록</button>
                </div>
            </form>
        </div>
        <div class="col-sm-12 col-md-8">
            <form action="{% url 'beauty:recommend_scrap' %}" method="POST">
                {% csrf_token %}
                <div class="scroll-wrap mb-1 result-table">
                    <div class="scrolling table-responsive scrollbar-lady-lips thin square">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="vid-select text-center"><span><i class="fa fa-check"></i></span></th>
                                    <th>추천 동영상</th>
                                    <th>조회수</th>
                                    <th>포함 화장품</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for video in videos %}
                                <tr>
                                    <td>
                                        <div class="custom-control custom-checkbox d-inline">
                                            <input type="checkbox" class="custom-control-input" name="video_id"
                                                id="customCheck{{ video.id }}" value="{{ video.id }}">
                                            <label class="custom-control-label" for="customCheck{{ video.id }}"></label>
                                        </div>
                                    </td>
                                    <td><a href="http://{{ video.yt_url }}" target="_blank">{{ video.title }}</a>
                                    </td>
                                    <td class="text-right">{{ video.hits }}</td>
                                    <td class="big-cate">
                                        <ul class="m-0 mt-1">
                                            {% for cosmetic in video.cosmetic.all %}
                                            {% if cosmetic in cosmetics %}
                                            <li class="mb-1"><i class="fa fa-smile-o mr-1" aria-hidden="true"></i>{{ cosmetic }} </li>
                                            {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <input type="hidden" name="curr_query" value="{{ request.GET.urlencode }}">
                <div class="text-right">
                    <button type="submit" class="btn btn-primary mt-auto col-4 col-sm-4 col-md-4 col-lg-3">동영상
                        스크랩</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

beauty/templates/beauty/cosmetic_edit.html
{% load custom_tags %}

<form action="" method="post">
    {% csrf_token %}
    {{ num }}번 비디오
    <br>
    {% for cos in row_cos %}
    {% if cos != "" %}
    <textarea name="{{num}},{{forloop.counter0}}" id="" cols="180" rows="2">{{cos}}</textarea>
    <br>
    {% endif %}
    {% endfor %}
    <input type="submit">
    <input type="submit" name="add" value="add">

    {% load mathfilters %}
    <a href="{% url 'beauty:cosmetic_edit' num|add:1 %}">다음 동영상 편집</a>
    <hr />
</form>