accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/<str:kind>', views.profile, name='profile'),
    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),
    # path('nickname_change/', views.MyNicknameChangeView.as_view(), name='nick_change'),
    path('video_scrap_processing', views.video_scrap_processing, name='video_scrap_processing'),
    path('cosmetic_scrap_processing', views.cosmetic_scrap_processing, name='cosmetic_scrap_processing'),
]

beauty/urls.py
from django.urls import path
from . import views, views_data

app_name = 'beauty'

urlpatterns = [
    path('create_test_DB', views_data.create_test_DB, name="create_test_DB"),
    path('create_test_csv', views_data.create_test_csv, name="creat_test_csv"),
    path('convert_xlsx_to_csv', views_data.convert_xlsx_to_csv, name="convert_xlsx_to_csv"),
    path('create_category_csv', views_data.create_category_csv, name="create_category_csv"),
    path('cosmetic_edit/<int:num>', views_data.cosmetic_edit, name="cosmetic_edit"),
    path('processing_csv', views_data.processing_csv, name="processing_csv"),

    path('', views.home, name="home"),
    path('video/', views.video_list, name="video_list"),
    path('video/<str:period>', views.video_list, name="video_list"),
    path('video_scrap', views.video_scrap, name="video_scrap"),

    path('cosmetic/', views.cosmetic_list, name="cosmetic_list"),
    path('cosmetic/<str:kind>', views.cosmetic_list, name="cosmetic_list"),
    path('cosmetic_scrap', views.cosmetic_scrap, name="cosmetic_scrap"),

    path('combine/result', views.combine_result, name="combine_result"),
    path('combine_processing', views.combine_processing, name="combine_processing"),

    path('combine/', views.combine_cosmetic, name="combine_cosmetic"),
    path('combine/<str:kind>', views.combine_cosmetic, name="combine_cosmetic"),
    
    path('cosmetic_pick', views.cosmetic_pick, name="cosmetic_pick"),
    path('cosmetic_delete', views.cosmetic_delete, name="cosmetic_delete"),
    path('cosmetic_reset', views.cosmetic_reset, name="cosmetic_reset"),

    path('cosmetic_save', views.cosmetic_save, name="cosmetic_save"),
    path('recommend_scrap', views.recommend_scrap, name="recommend_scrap"),

    path('search', views.search, name="search"),
]

veauty_inside/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('', lambda r:redirect('beauty:home'), name='root'),
    path('admin/', admin.site.urls),
    path('beauty/', include('beauty.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser, UserManager as BaseUserManager
from beauty.models import Cosmetic, Video
from django.utils import timezone

class UserManager(BaseUserManager):
    def create_superuser(self, *args, **kwargs):
        return super().create_superuser(gender=self.model.GENDER_OTHER, nickname="", birth="", *args, **kwargs)

class User(AbstractUser):
    GENDER_MALE = 'm'
    GENDER_FEMALE = 'f'
    GENDER_OTHER = 'o'
    CHOICES_GENDER = (
        (GENDER_MALE, '남성'),
        (GENDER_FEMALE, '여성'),
        (GENDER_OTHER, '기타'),
    )
    gender = models.CharField(max_length=1, choices=CHOICES_GENDER)
    nickname = models.CharField(max_length=50)
    birth = models.DateField(auto_now=False, auto_now_add=False, default=timezone.localtime())
    cosmetic = models.ManyToManyField(Cosmetic,related_name="cosmetics")
    my_cosmetic = models.ManyToManyField(Cosmetic,related_name="my_cosmetics")
    video = models.ManyToManyField(Video)

    def __str__(self):
        return self.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        class_update_fields = ['password1', 'password2']
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'nickname',
            'password1',
            'password2',
            'birth',
            'gender',
        )
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'nickname': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'birth': forms.DateInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'gender': forms.Select(
                attrs={
                    'class': 'form-control',
                }
            ),
        }

accounts/views.py
from django.contrib.auth.forms import UserChangeForm
from django.shortcuts import render, redirect, resolve_url, get_object_or_404
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from .forms import SignupForm
from .models import User
from beauty.models import Bigcate, Video, Cosmetic
from beauty.views import create_recomend
import copy
from django.contrib.auth.views import PasswordChangeView
from django.contrib import messages

User = get_user_model()

class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name="accounts/signup.html"

    def get_success_url(self):
        next_url = self.request.GET.get('next') or 'profile'
        return resolve_url(next_url)

    def form_valid(self, form):
        user = form.save()
        auth_login(self.request, user)
        return redirect(self.get_success_url())

signup = SignupView.as_view()

class LoginView(auth_views.LoginView):
    template_name="accounts/login.html"
    redirect_authenticated_user = True    

login = LoginView.as_view()

@login_required
def profile(request, kind=""):
    contexts = {}
    contexts['taps'] = ['video', 'interest', 'my']
    contexts['kind'] = kind

    if kind == contexts['taps'][0] or kind == "":
        kind = contexts['taps'][0]
        contexts['kind'] = kind
        contexts['videos'] = request.user.video.all()
        contexts['big_categories'] = Bigcate.objects.all()

        return render(request, 'accounts/video_table.html', contexts)
    elif kind == contexts['taps'][1]:
        contexts['cosmetics'] = request.user.cosmetic.all()

        return render(request, 'accounts/cosmetic_table.html', contexts)
    elif kind == contexts['taps'][2]:
        contexts['cosmetics'] = request.user.my_cosmetic.all()

        return render(request, 'accounts/cosmetic_table.html', contexts)
    else:
        return redirect("profile", contexts['taps'][0])

@login_required
def video_scrap_processing(request):
    if request.method == 'POST':
        videos = Video.objects.filter(pk__in=request.POST.getlist('video_id')) or ''
        request.user.video.remove(*videos)
        if videos:
            messages.success(request, '선택하신 동영상들이 스크랩 취소되었습니다.')
        else:
            messages.warning(request, '스크랩을 취소할 동영상을 선택해주세요.')
    return redirect("profile", 'video')

@login_required
def cosmetic_scrap_processing(request):
    if request.method == 'POST':
        cosmetics_list = request.POST.getlist('cosmetic_id') or ''
        if not cosmetics_list:
            messages.warning(request, '화장품을 선택해주세요.')
            return redirect("profile", request.POST['kind'])

        elif request.POST['selection'] == 'cancel':
            cosmetics = Cosmetic.objects.filter(pk__in=cosmetics_list)
            if request.POST['kind'] == 'interest':
                request.user.cosmetic.remove(*cosmetics)
                messages.success(request, '선택하신 화장품을 관심 화장품에서 제거했습니다.')
            elif request.POST['kind'] == 'my':
                request.user.my_cosmetic.remove(*cosmetics)
                messages.success(request, '선택하신 화장품을 내 화장품에서 제거했습니다.')
        elif request.POST['selection'] == 'combine':
            querystring = (lambda x: '?c=' + '&c='.join(x) if x else "?")(cosmetics_list)

            response = redirect("beauty:combine_result")
            response['Location'] += querystring
            return response
            
    return redirect("profile", request.POST['kind'])


class MyPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('profile')
    template_name = 'accounts/password_change.html'

    def form_valid(self, form):
        messages.info(self.request, '암호 변경을 완료했습니다.')
        return super().form_valid(form)


# class MyNicknameChangeView(User):
#     class Meta:
#         model = get_user_model()
#         fields = ['nickname']

accounts/templates/accounts/base.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accounts_style.css' %}">
    <link rel="stylesheet" href="{% static 'hello_kiddie.css' %}">
{% endblock %}

{% block body %}
    {% block content %}
    {% endblock %}
{% endblock %}

accounts/templates/accounts/cosmetic_table.html
{% extends "accounts/profile.html" %}

{% block table %}
<form action="{% url 'cosmetic_scrap_processing' %}" method="post">
    {% csrf_token %}
    <div class="scroll-wrap mb-1 profile-table">
        <div class="scrolling table-responsive scrollbar-lady-lips thin square">
            <table class="table">
                <thead>
                    <tr>
                        <th class="vid-select text-center"><span><i class="fa fa-check"></i></span></th>
                        <th>cosmetic</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cosmetic in cosmetics %}
                    <tr>
                        <td>
                            <div class="custom-control custom-checkbox d-inline">
                                <input type="checkbox" class="custom-control-input" name="cosmetic_id"
                                    id="customCheck{{ cosmetic.id }}" value="{{ cosmetic.id }}">
                                <label class="custom-control-label" for="customCheck{{ cosmetic.id }}"></label>
                            </div>
                        </td>
                        <td>{{ cosmetic.name }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="scrap-wrap">
        <input type="hidden" name="kind" value="{{ kind }}">
        <div class="text-right">
            <button type="submit" class="btn btn-primary mt-auto" name="selection" value="combine">화장품
                조합하기</button>
            <button type="submit" class="btn btn-primary mt-auto" name="selection" value="cancel">등록 취소하기</button>
        </div>
    </div>
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}

{% block content %}

<div class="container">
    <div class="row d-flex justify-content-center align-content-center">
        <div class="col-md-8 col-lg-5 px-5 py-4 border border-primary">
            <div class="row d-flex justify-content-center">
                <h1><a href="{% url 'root' %}">Veauty Inside</a></h1>
            </div>
            <div class="row d-flex justify-content-center">
                <p>스타 유튜버들의 잇템을 공유하세요!</p>
            </div>


            <div class="row d-flex justify-content-center">
                <form action="" method="post" class="w-100 p-1">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                    <div class="w-100 alert alert-danger alert-dismissable show fade mt-1" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                        {{ error }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    <input type="text" name="username" class="form-control mb-2" autofocus required id="id_username"
                        placeholder="ID">
                    <input type="password" name="password" class="form-control mb-2" required id="id_password"
                        placeholder="Password">

                    <button type="submit" class="btn btn-outline-primary w-100">로그인</button>
                </form>
            </div>
            <hr />
            <div class="row d-flex justify-content-center">
                <p>계정이 없으신가요?</p>
            </div>
            <div class="row d-flex justify-content-center">
                <button type="submit" class="btn btn-outline-primary w-100 m-1"
                    onclick='location.href="{% url "signup" %}";'>회원가입</button>
            </div>
            <hr />
            <div class="row d-flex justify-content-center">
                <p>회원가입 없이</p>
            </div>
            <div class="row d-flex justify-content-center">
                <a href="{% url 'beauty:combine_cosmetic' %}">둘러보기</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/nickname_change.html
{% extends "accounts/base.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>

        </table>
        <div class="container" id="PasswordReset">
            <div class="d-flex justify-content-center">
                <div id="PasswordR">
                    <h2>닉네임 변경</h2>
                    <p>
                        <input name="old_nickname" class="form-control" required id="nickname"
                               placeholder="old nickname">
                    </p>
                    <p>
                        <input name="new_nickname" class="form-control" required id="nickname"
                               placeholder="new nickname">
                    </p>
                    <input type="submit"/>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends "accounts/base.html" %}

{% block content %}


    <form action="" method="post">
        {% csrf_token %}
        <table>
            {#            {{ form.as_table }}#}

        </table>
        <div class="container" id="PasswordReset">
            <div class="d-flex justify-content-center">

                <div id="PasswordR">
                    <h2>비밀번호 변경</h2>
                    {% for field in form %}
                        <p>
                            {% for error in field.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </p>
                    {% endfor %}
                    <p>
                        <input type="password" name="old_password" class="form-control" required id="id_password1"
                               placeholder="Old Password">
                    </p>
                    <p>
                        <input type="password" name="password1" class="form-control" required id="id_password1"
                               placeholder="Password">
                    </p>

                    <p>
                        <input type="password" name="password2" class="form-control" required id="id_password2"
                               placeholder="Password Confirmation">
                    </p>
                    <p>
                        <input type="submit"/>
                    </p>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "beauty/base.html" %}

{% block content %}
<div class="container">
    <div class="row d-flex justify-content-center align-items-center" style="height:15vh;">
        <h2>{{ user.nickname }}<small>님</small></h2>
{#        <a href="{% url "password_change" %}">비밀번호 변경하기</a>#}
{#        <a href="{% url "nickname_change" %}">닉네임 변경하기</a>#}
    </div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissable show fade mt-1" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if kind == taps.0 %} active {% endif %}" href="{% url 'profile' taps.0 %}">스크랩 동영상</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if kind == taps.1 %} active {% endif %}" href="{% url 'profile' taps.1 %}">관심 화장품</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if kind == taps.2 %} active {% endif %}" href="{% url 'profile' taps.2 %}">내 화장품</a>
        </li>
    </ul>
    {% block table %}
    {% endblock %}

</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row d-flex justify-content-center align-content-center">
        <div class="col-sm-0 col-md-6 col-lg-5 align-content-center" style="overflow: hidden" id="signup-img">
            <img src="{% static 'signup.jpeg' %}" style="width:100%; height:100%;">
        </div>
        <div class="col-10 col-md-6 col-lg-5 px-5 py-4 border border-primary">
            <div class="row d-flex justify-content-center">
                <h1><a href="{% url 'root' %}">Veauty Inside</a></h1>
            </div>
            <div class="row d-flex justify-content-center">
                <p>스타 유튜버들의 잇템을 공유하세요!</p>
            </div>

            <div class="row d-flex justify-content-center">
                {% for field in form %}
                {% for error in field.errors %}
                <div class="w-100 alert alert-danger alert-dismissable show fade m-1" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    {{ error }}
                </div>
                {% endfor %}
                {% endfor %}
                <form action="" method="post" class="w-100 p-1">
                    {% csrf_token %}
                    <input type="text" name="username" class="form-control mb-2" maxlength="150" autofocus required
                        id="id_username" placeholder="ID">
                    <input type="text" name="first_name" class="form-control mb-2" maxlength="30" id="id_first_name"
                        placeholder="First name">
                    <input type="text" name="last_name" class="form-control mb-2" maxlength="150" id="id_last_name"
                        placeholder="Last name">
                    <input type="text" name="nickname" class="form-control mb-2" maxlength="50" required
                        id="id_nickname" placeholder="NickName">
                    <input type="password" name="password1" class="form-control mb-2" required id="id_password1"
                        placeholder="Password">
                    <input type="password" name="password2" class="form-control mb-2" required id="id_password2"
                        placeholder="Password Confirmation">
                    <input type="text" name="birth" class="form-control mb-2" required id="id_birth"
                        placeholder="YYYY-MM-DD">
                    <select name="gender" class="form-control mb-2" required id="id_gender">
                        <option value="m">남성</option>
                        <option value="f">여성</option>
                        <option selected="selected">성별</option>
                    </select>
                    <button type="submit" class="btn btn-outline-primary w-100">가입하기</button>
                </form>
            </div>
            <hr />
            <div class="row  d-flex justify-content-center">
                <p>회원가입 없이</p>
            </div>
            <div class="row  d-flex justify-content-center">
                <a href="{% url 'beauty:combine_cosmetic' %}">둘러보기</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/video_table.html
{% extends "accounts/profile.html" %}

{% block table %}
<form action="{% url 'video_scrap_processing' %}" method="post">
    {% csrf_token %}
    <div class="scroll-wrap mb-1 profile-table">
        <div class="scrolling table-responsive scrollbar-lady-lips thin square">
            <table class="table">
                <thead>
                    <tr>
                        <th class="vid-select text-center"><span><i class="fa fa-check"></i></span></th>
                        <th class="text-center">랭킹</th>
                        <th>제목</th>

                        {% for big_category in big_categories %}
                        <th>
                            {{ big_category }}
                        </th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for video in videos %}
                    {% load mathfilters %}
                    <tr>
                        <td class="vid-select">
                            <div class="custom-control custom-checkbox d-inline">
                                <input type="checkbox" class="custom-control-input" name="video_id"
                                    id="customCheck{{ video.id }}" value="{{ video.id }}">
                                <label class="custom-control-label" for="customCheck{{ video.id }}"></label>
                            </div>
                        </td>
                        <td>
                            {% if pageNum %}
                            {{ pageNum|mul:PAGE_ROW_COUNT| sub:PAGE_ROW_COUNT |add:forloop.counter }}
                            {% else %}
                            {{ forloop.counter }}
                            {% endif %}
                        </td>
                        <td width="350em" nowrap><a href="{{ video.yt_url }}" target="_blank">{{ video.title }}</a></td>

                        {% for big_category in big_categories %}
                        <td class="big-cate">
                            <ul class="m-0">
                                {% for cosmetic in video.cosmetic.all %}

                                {% if cosmetic.category.bigcate == big_category %}
                                <li>
                                    {{ cosmetic.name }}
                                </li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="scrap-wrap">
        <div class="text-right">
            <button type="submit" class="btn btn-primary mt-auto">스크랩 취소하기</button>
        </div>
    </div>
</form>
{% endblock %}